[package]
name = "blogen"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.8.0"
hotwatch = "0.4"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
walkdir = "2"
axum = "0.5.6"
tower-http = { version = "0.3", features = ["fs"] }
